language: cpp

os:
  - linux
  - osx

addons:
  artifacts:
    s3_region: "eu-west-1"
    debug: true
    paths:
    - build/obj-2-fieldap.$TRAVIS_OS_NAME
  apt:
    packages:
      - gcc-5
      - g++-5
      - libassimp-dev
    sources:
      - ubuntu-toolchain-r-test

script:
  - if [ $TRAVIS_OS_NAME == linux ]; then g++-5 -std=c++14 process/*.cpp externals/*.cc main.cpp -lstdc++ -o build/obj-2-fieldap.$TRAVIS_OS_NAME; fi
  - if [ $TRAVIS_OS_NAME == osx ];   then clang++ -std=c++14 process/*.cpp externals/*.cc main.cpp -lstdc++ -o build/obj-2-fieldap.$TRAVIS_OS_NAME; fi

notifications:
  email: false
