version: 1.0.{build}-{branch}
os:
  - Visual Studio 2019

environment:
  matrix:
    - TOOLSET: vs2019

platform:
  - x64

configuration:
  - Release

before_build:  
  - vcpkg install assimp:x64-windows
  - ps: (Get-Content version.h).replace('[BUILD_VERSION]', '{version}') | Set-Content version.h


cache:
  - c:\tools\vcpkg\installed\

build:
  project: build/obj-2-fieldap.sln

after_build:
  - cd build && del /F /Q obj-2-fieldap.zip && 7z a obj-2-fieldap.zip *.exe

artifacts:
  - path: build/obj-2-fieldap.zip
    name: binary
    type: zip
