os:
  - Visual Studio 2015

environment:
  matrix:
    - TOOLSET: vs2015

configuration: Release

build:
  project: build/obj-2-fieldap.sln

after_build:  
  - cd build && del /F /Q obj-2-fieldap.zip && 7z a obj-2-fieldap.zip *.exe *.pdb

artifacts:
  - path: build/obj-2-fieldap.zip
    name: binary
    type: zip
